/-
This file was generated by Aristotle.

Lean Toolchain version: leanprover/lean4:v4.20.0-rc5
Mathlib version: d62eab0cc36ea522904895389c301cf8d844fd69 (May 9, 2025)
-/

/-
This module proves a corollary of the Hahn-Banach theorem: in a Banach space, for any non-zero vector $v$, there exists a continuous linear functional $\varphi$ such that $\varphi(v) \neq 0$.

The main theorem is `exists_dual_eval_ne_zero`. It uses `SeparatingDual.exists_ne_zero` from Mathlib, which encapsulates this consequence of the Hahn-Banach theorem.

Note: The theorem is stated for any `NormedSpace` over an `RCLike` field (like $\mathbb{R}$ or $\mathbb{C}$), and assumes `CompleteSpace` (Banach space), although strictly speaking, completeness is not required for this specific corollary (it holds in any normed vector space), but the user specifically asked for Banach spaces. The `SeparatingDual` instance is automatically available for normed spaces over `RCLike` fields.
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

#check SeparatingDual.exists_ne_zero

theorem exists_dual_eval_ne_zero {𝕜 : Type*} [RCLike 𝕜] {V : Type*} [NormedAddCommGroup V] [NormedSpace 𝕜 V] [CompleteSpace V] {v : V} (hv : v ≠ 0) : ∃ φ : V →L[𝕜] 𝕜, φ v ≠ 0 := by
  -- By the Hahn-Banach theorem, since $v \neq 0$, there exists a continuous linear functional $\phi$ such that $\phi(v) \neq 0$.
  apply SeparatingDual.exists_ne_zero; assumption