import Mathlib
/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-/

/-
We have formalized two theorems regarding topological vector spaces over $\mathbb{R}$.

1. `unique_tvs_topology_of_finiteDimensional`: This theorem states that for a finite-dimensional real vector space $E$, the topology that makes it a Hausdorff topological vector space is unique. This implies that the usual topology on $\mathbb{R}^n$ is the only such topology.

2. `discrete_tvs_over_real_is_zero`: This theorem states that if a topological vector space over $\mathbb{R}$ has the discrete topology, then it must be the zero space (i.e., a subsingleton). This is proven by showing that if the space were not the zero space, the scalar multiplication map would imply that $\{0\}$ is open in $\mathbb{R}$, which is false.
-/

#check unique_topology_of_t2

/-
The topology on a finite-dimensional real vector space that makes it a Hausdorff topological vector space is unique.
-/
theorem unique_tvs_topology_of_finiteDimensional
  {E : Type*} [AddCommGroup E] [Module ℝ E] [FiniteDimensional ℝ E]
  (t1 t2 : TopologicalSpace E)
  (h1 : @IsTopologicalAddGroup E t1 _)
  (h2 : @ContinuousSMul ℝ E _ _ t1)
  (h3 : @T2Space E t1)
  (h4 : @IsTopologicalAddGroup E t2 _)
  (h5 : @ContinuousSMul ℝ E _ _ t2)
  (h6 : @T2Space E t2) :
  t1 = t2 := by
    -- Let $T_1$ be the topology on $E$ determined by $t1$ and $T_2$ be the topology on $E$ determined by $t2$.
    set T1 : TopologicalSpace E := t1
    set T2 : TopologicalSpace E := t2;
    -- Since $E$ is finite-dimensional, the topology on $E$ determined by $t1$ is the same as the topology on $E$ determined by $t2$.
    have h_top_eq : T1 = T2 := by
      have h_iso : Nonempty (E ≃ₗ[ℝ] (Fin (Module.finrank ℝ E) → ℝ)) := by
        exact ⟨ ( Module.finBasis ℝ E ).equivFun ⟩
      simp +zetaDelta at *;
      -- Let $\phi: E \to \mathbb{R}^n$ be an isomorphism.
      obtain ⟨ϕ, hϕ⟩ : ∃ ϕ : E ≃ₗ[ℝ] (Fin (Module.finrank ℝ E) → ℝ), True := by
        exact ⟨ h_iso.some, trivial ⟩;
      -- Since $\phi$ is a linear isomorphism, it is a homeomorphism with respect to any topology on $E$ that makes it a topological vector space.
      have h_homeo : ∀ (t : TopologicalSpace E), IsTopologicalAddGroup E → ContinuousSMul ℝ E → T2Space E → (Continuous ϕ ∧ Continuous ϕ.symm) := by
        intro t ht1 ht2 ht3
        have h_homeo : Continuous ϕ := by
          -- Since $E$ is finite-dimensional, any linear map from $E$ to $\mathbb{R}^n$ is continuous.
          have h_linear_cont : ∀ (f : E →ₗ[ℝ] (Fin (Module.finrank ℝ E) → ℝ)), Continuous f := by
            exact?;
          exact h_linear_cont ϕ.toLinearMap
        have h_homeo_symm : Continuous ϕ.symm := by
          have h_homeo_symm : Continuous (ϕ.symm : (Fin (Module.finrank ℝ E) → ℝ) → E) := by
            have h_cont : Continuous (fun x : Fin (Module.finrank ℝ E) → ℝ => ∑ i, x i • ϕ.symm (Pi.single i 1)) := by
              fun_prop
            convert h_cont using 1;
            ext x; simp +decide [ ← map_smul, ← map_add ] ;
            rw [ ← map_sum ];
            exact congr_arg _ ( by ext i; simp +decide [ Pi.single_apply ] );
          exact h_homeo_symm
        exact ⟨h_homeo, h_homeo_symm⟩;
      have h_top_eq : ∀ (t : TopologicalSpace E), IsTopologicalAddGroup E → ContinuousSMul ℝ E → T2Space E → t = TopologicalSpace.induced ϕ (by infer_instance) := by
        intro t ht1 ht2 ht3;
        have := h_homeo t ht1 ht2 ht3;
        refine' le_antisymm _ _;
        · -- Since ϕ is continuous with respect to t, the induced topology is finer than t.
          have h_induced_finer : t ≤ TopologicalSpace.induced ϕ (by infer_instance) := by
            have h_cont : Continuous ϕ := this.left
            exact?;
          exact h_induced_finer;
        · bound;
          rw [ le_iff_nhds ];
          intro x;
          have := right.tendsto ( ϕ x );
          rw [ nhds_induced ];
          rw [ le_nhds_iff ];
          intro s hx hs;
          exact ⟨ ϕ.symm ⁻¹' s, this ( hs.mem_nhds ( by simpa ) ), by aesop_cat ⟩;
      rw [ h_top_eq t1 h1 h2 h3, h_top_eq t2 h4 h5 h6 ];
    exact h_top_eq

/-
The only topological vector space over $\mathbf{R}$ with the discrete topology is the zero space.
-/
theorem discrete_tvs_over_real_is_zero
  (E : Type*) [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
  [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [DiscreteTopology E] :
  Subsingleton E := by
    exact PreconnectedSpace.trivial_of_discrete
